### ISSUE TITLE
Aliens in Critical who are then hit with a melee weapon will die slowly from OXY damage

### ISSUE THREAD

**Issue by rahlzel** [jaggerestep/ColonialMarines#114]
Yeah, I know. Wild. Just saw this happen with 2 other players on the server. 

1. Alien gets shot until it's in critical health (not dead yet)
2. Marine hits alien with a cable coil once
3. Alien never regenerates or leaves crit. BRUTE damage doesn't change and OXY damage rises until the alien dies.

I just confirmed this on my test server. Really weird.

**Comment by apophis775** [comment]
Any alien, who is in Crit, not on weeds slowly dies.
This is intentional.

**Comment by rahlzel** [comment]
Why is that?

**Comment by Infernus444** [comment]
Well, their HP is below 0%, meaning that they will die in a minute if aliens don't drag it to weeds, and that is where the O2 damage is coming from. They can only recover from critical when on weeds.

[Unless they loose O2 while on weeds when struck by melee weapons, than it is a bug]

**Comment by rahlzel** [comment]
Aren't they supposed to be able to heal slowly through critical? There's no way of capturing an alien if it's shot until critical and then handcuffed. It'll just suddenly die as it's getting dragged away. I've seen this happen.

**Comment by Infernus444** [comment]
There is. Inaprovaline stops oxy damage, cyro and sleeper heals brute damage.

Invalid.

**Comment by apophis775** [comment]
Aliens can still "bleed out" and die
Oxy damage, is used as a catch-all.
