### ISSUE TITLE
Recommendation: Spitter nerf

### ISSUE THREAD

**Issue by rahlzel** [jaggerestep/ColonialMarines#134]
SASoperative told me that a single Spitter was able to kill a 4-person group (the queen was dead, so he was slashing correctly). Then, it assassinated the rest of the Sulaco crewmembers that were alone, one by one (I saw some of it myself).

The next round, he and I tested the Spitter, and I have to admit - a 2-second interval between spits should probably be adjusted. With lag, the interval feels more like 3-4 seconds, but I was able to keep a single (blank) human mob down on the ground for longer than the spit needed to recharge.

Also, though it might be intended, both spit verbs (Weak and regular) are in the Alien tab.

I'm pretty sure the spit timer is defined here:
https://github.com/jaggerestep/ColonialMarines/blob/master/code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm#L227

And the Weak Neurotoxin is below it at 4 seconds: https://github.com/jaggerestep/ColonialMarines/blob/master/code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm#L261

I recommend increasing the regular spit interval to 5-10 seconds, which with lag will feel more like 6-11 seconds.

**Comment by apophis775** [comment]
Adjusted.
Also, intentional for each of them to have their level of toxin, and the one below.
