### ISSUE TITLE
[Map] Need health analyzers in the squad medic prep rooms

### ISSUE THREAD

**Issue by rahlzel** [jaggerestep/ColonialMarines#138]

**Comment by Infernus444** [comment]
Doesn't each medkit have one? And there should be 3 regular medkits.

**Comment by rahlzel** [comment]
The medkits on the other side of the station in the Medbay Storage have them, but the Advanced Medkits don't. They have splints instead. In fact, you could perhaps replace the splints on the rack with health analyzers.

**Comment by Infernus444** [comment]
Sure, but there are still 3 regular medkits with health analyzers in each prep room.

**Comment by rahlzel** [comment]
Crap. I didn't see those. There's a whole stack of things and only one item is visible. Can you nudge some things around to make them easier to see?

**Comment by Infernus444** [comment]
alt + click the floor tile under it, and it will give you the whole list without any lag.

**Comment by apophis775** [comment]
Closing, since, this resolved itself.
