### ISSUE TITLE
Another spitter nerf

### ISSUE THREAD

**Issue by Infernus444** [jaggerestep/ColonialMarines#140]
I just witnessed him killing 10 marines.
You CAN'T have an alien with BOTH strong ranged and close attacks. It is against the nature of balance.
Sentinel
	damagemin = 27
	damagemax = 34
Spitter
	damagemin = 35
	damagemax = 40 

Praetorian
	damagemin = 40
	damagemax = 45

Hunter
	damagemin = 30
	damagemax = 35

What the actual fuck?

Armors don't protect legs and arms, so their attack cant be blocked nor softened.

We can either have ranged or close combat aliens, not both.

**Comment by Infernus444** [comment]
He just killed 20 more while I was posting this, and I am not even lying...

**Comment by apophis775** [comment]
Taken care of
